# Jekyll Configuration for AI Documentation Framework Wiki
title: "AI Documentation Framework"
description: "Comprehensive AI-Optimized Documentation System for Multi-Application Projects"
baseurl: "/ai-doc-framework"
url: "https://zsarir.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Sass/SCSS settings
sass:
  sass_dir: assets/css
  style: compressed

# Build settings for GitHub Pages
github: [metadata]

# Permalinks
permalink: pretty
